/**
 * Formatting a day into the context the shared proactive-action prompt expects.
 *
 * The Day view's Actions are the assistant's proposals - "message Priya the build", "add a reminder"
 * - generated by the lead's shared proactive-action policy. That policy takes the day as formatted
 * strings (todos, calls); this turns our sessions + tasks into those strings. Pure.
 */

import type { TimelineSession } from './timelineModel'
import type { DayTask } from './dayModel'

/** The day's conversations as the "calls" context: title, who, and what happened. */
export function formatCallsForActions(sessions: TimelineSession[]): string {
  return sessions
    .filter(s => s.summary.headline.trim().length > 0)
    .map(s => {
      const who = s.summary.people.length > 0 ? ` with ${s.summary.people.join(', ')}` : ''
      const decisions = s.summary.decisions.length > 0 ? ` Decided: ${s.summary.decisions.join('; ')}.` : ''
      return `- ${s.summary.title}${who}: ${s.summary.headline}${decisions}`
    })
    .join('\n')
}

/** The day's open tasks as the "todos" context, each with the conversation it came from. */
export function formatTodosForActions(tasks: DayTask[]): string {
  return tasks
    .filter(t => !t.done)
    .map(t => `- ${t.text} (from ${t.sessionTitle})`)
    .join('\n')
}
